#!/bin/bash

read -p "Enter The Data Name You Want To Connect: " data_name

if [ -d "./data/$data_name" ]; then
    echo "You Connected To Data Successfully"
    cd "./data/$data_name"
    current_dir=$(basename "$PWD")
    echo "using: $current_dir"
    echo "Please select a query to execute:"
    PS3="Enter your choice: "
    options=("Create Table" "Drop Table" "List Tables" "Insert into Table" "Select from Table" "Delete from Table" "Update Table" "Exit")

    select opt in "${options[@]}"
    do
        case $opt in
            "Create Table")
                echo "You chose to create tables."
                ../../createtable
                ;;
            "Drop Table")
                echo "You chose to drop tables."
               ../../droptable
                ;;
            "List Tables")
                echo "You chose to list tables."
                ../../listtable
                ;;
            "Insert into Table")
                echo "You chose to insert into tables."
               ../../insertintotable
                ;;
            "Select from Table")
                echo "You chose to select from tables."
                ../../Selectfromtable
                ;;
            "Delete from Table")
                echo "You chose to delete from tables."
                ../../deletefromtable
                ;;
            "Update Table")
                echo "You chose to update tables."
                ../../updatetable
                ;;
            "Exit")
                echo "Exiting."
                break
                ;;
            *)
                echo "Invalid option $REPLY"
                ;;
        esac
    done
else 
    echo "Data Doesn't Exist"
fi
