#!/bin/bash

# ---------------------------enter the database name to delete
read -p "Enter The Database Name: " data_name

# ---------------------------Check if the database exists
if [[ -d "./data/$data_name" ]]; then

    rm -r "./data/$data_name"
	echo "Database deleted Successfully"

else
    echo "This Database does not exist"
fi
