#!/bin/bash

 dir_list=$(find ./data -maxdepth 1 -type d -printf "%P\n" 2>/dev/null)
if [ -z "$dir_list" ]; then
    echo "list is empty"
else
    for dir in $dir_list; do
        echo "$dir"
    done
fi