#!/bin/bash

echo "Please select a query to execute:"

#-----------------------------------choose which query you want to start

PS3="Enter your choice: "
options=("Create Data" "Connect To Data" "List Data" "Drop Data" "Exit")


select opt in "${options[@]}"
do
    case $opt in
        "Create Data")
            echo "You chose to create Data."
            ./createdata
            ;;
        "Connect To Data")
            echo "You chose to connect to Data."
            ./connectTodata
            ;;
        "List Data")
            echo "You chose to list Data."
           ./list
            ;;
        "Drop Data")
            echo "You chose to Drop Data."
            ./dropdata
            ;;
        "Exit")
            break
            ;;
        *)
            echo "Invalid option $REPLY"
            ;;
    esac
done
